"""The seam between a decided command and whatever carries it out.

M3 has one implementation and it is a loopback: it writes the desired value to
the control point and reports the same value back on the status point. It
models no fan, no airflow and no cooling — proving that the decision is right
and that the logical actuator follows it is what the milestone is for.

The protocol exists so that an Edge or device adapter can take its place
without :mod:`ai_greenhouse.control.automation` changing. It is deliberately one
method on one interface: a registry, a dispatcher hierarchy or a plugin
framework would be infrastructure for a second implementation that does not
exist yet.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol
from uuid import UUID

from ai_greenhouse.points.models import DataQuality
from ai_greenhouse.telemetry.schemas import TelemetrySampleRecord
from ai_greenhouse.telemetry.service import TelemetryService

RESULT_QUALITY: DataQuality = DataQuality.SIMULATED
"""How far a value the loopback adapter reports can be trusted.

``simulated`` is the honest answer: no instrument measured it, and the same
value is written on both points because the adapter is the fan. A device
adapter reporting a real contactor would use ``good`` instead, which is exactly
the distinction the column exists to carry.
"""


@dataclass(frozen=True, slots=True)
class ActuationRequest:
    """Everything an adapter needs to apply one command, and nothing else.

    The two sample identifiers are supplied rather than generated by the
    adapter. They are derived from the command, which is what makes a re-applied
    command write the same two samples instead of a second pair beside them, and
    that property must not depend on which adapter is installed.

    Attributes:
        command_id: The command being applied.
        control_point_id: Point carrying the desired state.
        status_point_id: Point carrying the state reported back.
        desired_value: The state asked for. ``True`` is on.
        executed_at: Instant to record both result samples at.
        control_sample_id: Identifier of the desired-state sample.
        status_sample_id: Identifier of the reported-state sample.
    """

    command_id: UUID
    control_point_id: UUID
    status_point_id: UUID
    desired_value: bool
    executed_at: datetime
    control_sample_id: UUID
    status_sample_id: UUID


class Actuator(Protocol):
    """Applies a decided command and records what the actuator reports back."""

    async def apply(self, request: ActuationRequest) -> None:
        """Apply one command, writing both result samples.

        Args:
            request: The command to apply and the identifiers to record it
                under.

        Raises:
            Exception: If the command could not be applied in full. The caller
                rolls the whole application back, so a partial result is never
                stored.
        """
        ...


class LoopbackActuator:
    """The M3 adapter: the fan is whatever the control point says it is.

    Both samples go through :class:`~ai_greenhouse.telemetry.service.
    TelemetryService`. Writing ``point_current_states`` any other way would give
    the projection a second author, and the idempotency and out-of-order rules
    it holds are only true because there is one.
    """

    def __init__(self, telemetry: TelemetryService) -> None:
        """Bind the adapter to the telemetry boundary of the current transaction.

        Args:
            telemetry: The write boundary both result samples go through.
        """
        self._telemetry: TelemetryService = telemetry

    async def apply(self, request: ActuationRequest) -> None:
        """Record the desired state and report the same value back.

        Args:
            request: The command to apply and the identifiers to record it
                under.
        """
        writes: tuple[tuple[UUID, UUID], ...] = (
            (request.control_point_id, request.control_sample_id),
            (request.status_point_id, request.status_sample_id),
        )
        for point_id, sample_id in writes:
            await self._telemetry.record_sample(
                TelemetrySampleRecord(
                    id=sample_id,
                    point_id=point_id,
                    value=request.desired_value,
                    observed_at=request.executed_at,
                    received_at=request.executed_at,
                    quality=RESULT_QUALITY,
                )
            )
