"""Declarative base and structural mixins shared by every domain module.

Enum storage convention
-----------------------
String enums are stored as ``VARCHAR`` with a ``CHECK`` constraint. Native
PostgreSQL enum types are deliberately not used: adding a value to a native enum
requires a migration and an exclusive lock, while a ``CHECK`` constraint can be
replaced in a single statement.

The convention is applied through :func:`enum_column` alone. Every enum column
in the project must be declared with that helper so the storage type, the
stored representation and the constraint naming stay identical across tables.
Do not mix in native enums.

Enum *values* are stored, not member names, so the database rows match the
strings used by the HTTP API.

These mixins are structural only. They carry no business behaviour, and no
generic base entity is provided on purpose.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import DateTime, Enum, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedColumn, declared_attr, mapped_column

from ai_greenhouse.infrastructure.database.metadata import metadata


class Base(DeclarativeBase):
    """Declarative base bound to the shared Milestone 0 metadata."""

    metadata = metadata


def utc_now() -> datetime:
    """Return the current instant as a timezone-aware UTC value."""
    return datetime.now(UTC)


def enum_column(
    enum_class: type[StrEnum],
    *,
    constraint_name: str,
    **kwargs: Any,
) -> MappedColumn[Any]:
    """Declare a string enum column as ``VARCHAR`` with a ``CHECK`` constraint.

    ``constraint_name`` feeds the ``ck_%(table_name)s_%(constraint_name)s``
    naming convention introduced in Milestone 0.
    """
    return mapped_column(
        Enum(
            enum_class,
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
            name=constraint_name,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        **kwargs,
    )


class UUIDPrimaryKeyMixin:
    """Primary key generated by the application, never by the database."""

    id: Mapped[UUID] = mapped_column(Uuid(), primary_key=True, default=uuid4)


class TimestampMixin:
    """UTC creation and modification instants stored as ``timestamptz``."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )


class StatusEnum(StrEnum):
    """Lifecycle of an entity. Rows are archived instead of being deleted."""

    ACTIVE = "active"
    ARCHIVED = "archived"


class StatusMixin:
    """Lifecycle column shared by entities that are archived rather than deleted."""

    @declared_attr
    @classmethod
    def status(cls) -> Mapped[StatusEnum]:
        return enum_column(
            StatusEnum,
            constraint_name="status",
            nullable=False,
            default=StatusEnum.ACTIVE,
            index=True,
        )
